### ISSUE TITLE
version of cloudlink in clients/meower-vanilla is incorrect

### ISSUE THREAD

**Issue by daydreamyyZX** [meower-media/archives#1]
meower-vanilla is built on cloudlink turbo (a MODIFIED cloudlink 3), and needs explicitly clturbo to function
the version of cloudlink provided in clients/meower-vanilla is cloudlink 3, the base version
meower-vanilla nor any clients past beta 4.8(?) can run with cloudlink 3 because they expect an extension with the name "networking", and instead receive one with the name "cloudlink", not letting the project load
manually changing all mentions of "networking" in the project.json to "cloudlink" does not work since clturbo is completely different from normal cl3

**Comment by EngineerRunner** [comment]
:nerd_face: 
> The code here won't be updated and isn't meant to be used.

**Comment by daydreamyyZX** [comment]
> 🤓
> 
> > The code here won't be updated and isn't meant to be used.

code
do you have are stupid or no

**Comment by williamhorning** [comment]
i don’t know why exactly CL3 is there, but everything there is just from the original repository so unless anyone has a copy of CL Turbo laying around, this doesn’t really have a fix

**Comment by tnix100** [comment]
The original repository never had CL Turbo, it’s located (in an old commit?) in Mike’s personal CL repo. However, I do agree that CL Turbo should be copied to this repository as it is needed for Meower Vanilla.

**Comment by daydreamyyZX** [comment]
> i don’t know why exactly CL3 is there, but everything there is just from the original repository so unless anyone has a copy of CL Turbo laying around, this doesn’t really have a fix

two people so far claim to have clturbo somewhere on their computers so

**Comment by daydreamyyZX** [comment]
well i found it
https://mikedev101.github.io/turbo_networking.js
